### ISSUE TITLE
CLI requires all components installed

### ISSUE THREAD

**Issue by cltrudeau** [barseghyanartur/faker-file#25]
I installed just the common components, but when I try to run the CLI version it complains it can't find DocxFileProvider. 

If the components truly are optional, then this shouldn't happen.

Python 3.11
faker-file==0.16
macOS 13.4

```
$ faker-file --help
Traceback (most recent call last):
  File "/Users/ctrudeau/s/py_vir_envs/RP/bin/faker-file", line 5, in <module>
    from faker_file.cli import main
  File "/Users/ctrudeau/s/py_vir_envs/RP/lib/python3.11/site-packages/faker_file/cli.py", line 15, in <module>
    from .providers.docx_file import DocxFileProvider
  File "/Users/ctrudeau/s/py_vir_envs/RP/lib/python3.11/site-packages/faker_file/providers/docx_file.py", line 4, in <module>
    from docx import Document
ModuleNotFoundError: No module named 'docx'
```

**Comment by barseghyanartur** [comment]
Well, it's mentioned in the docs, that for CLI all common components are required. Besides that, it's recommended to install CLI using pipx.

**Comment by cltrudeau** [comment]
I guess I missed that in the docks. No worries. Your tool, your prerogative.

**Comment by barseghyanartur** [comment]
@cltrudeau:

That's not what I meant. Obviously, it's made to soften the pain of other devs like me. Just thinking logically, trying to do what's best. Conditionally checking installed packages, loading every lazily is possible, but requires efforts and if not justified - is a waste of time.

As far as I can see, the main purpose of the CLI is to generate a dummy file for manual testing. Like, whenever I need to do manual testing and need different formats, instead of searching the internet, I just use CLI, which is installed using `pipx` on my local machine. Pipx creates isolated environments. No dependency hell.

For automated testing, it's indeed highly optional. You don't need any components, except `Faker`. Basic formats, like TXT, ZIP, TAR, BIN, CSV are then supported. Risks of dependency hell or inappropriate licenses is quite minimal.

What's your use-case?

**Comment by cltrudeau** [comment]
Sorry, didn't mean to come off snippy. Wasn't my intent. Was just playing with the tool and thought you'd want to know.

Conditional checking is a pain, I agree. A simple fix might be to wrap the loading piece in try/except and print out a message saying "need to pip install faker-file[common] to use the CLI"

**Comment by barseghyanartur** [comment]
Done in 0.16.1.

**Comment by barseghyanartur** [comment]
@cltrudeau:

Ah, I was just checking the statistics and found out you were mentioning this project in the podcast. 

One thing that hasn't been briefly mentioned in the docs, but probably one of the things you were wondering about.

The returned value of any file generation (whether you choose that to be a real file or bytes) is not really a string (path to the file) or bytes, but a wrapper around these objects. In case if files it's a `StringValue` and in case of bytes - `BytesValue`.
I have made a demo in Jupyter notebook for interactive presentations. If you're curious, you better run it from cloned repository (as it depends on a Django Kernel for Jupyter notebook, provided by `django-extensions` package).

```python
from faker import Faker
from faker_file.providers.docx_file import DocxFileProvider

FAKER = Faker()

FAKER.add_provider(DocxFileProvider)

file = FAKER.docx_file()

print(file)  # will print relative path to the file from the given `root_path` directory.
print(file.data["filename"])  # will print absolute path to the file
print(file.data["content"])  # will print the text content of the file
```

These objects do have metadata stored in a `data` property. Data contains a lot of handy information to support tests, but one common thing that every file format has is the `filename`, which is an absolute path to the file. The reasoning is briefly explained [here](https://faker-file.readthedocs.io/en/latest/index.html#filesystemstorage-example).
